### ISSUE TITLE
Bots do not respect Infected Mode.

### ISSUE THREAD

**Issue by Chenterito** [ineedbots/piw5_bot_warfare#4]
Tried it in "Infected" Game mode and added the bots to the survivors. there everything is going well. The problem occurs when a bot is infected, it appears with a weapon, when in the game mode classes the infected do not have weapons, they only have a knife. The point is that they do not respect the predefined classes of the game mode.

**Comment by ineedbots** [comment]
Should be fixed when the _class.gsc update gets pushed to plutonium

a080f586d424e3127daebcf691832548ae61c9e5

**Comment by Chenterito** [comment]
I've been testing and it gives a lot of errors and that makes bots always come out with JUGGERNAUT

**Comment by ineedbots** [comment]
I know, because right now, plutonium needs the updated _class.gsc, but it doesnt at this moment. (need to wait for an update)

Right now edit the _class.gsc yourself and change
Line number 1278
```
self notify( "giveLoadout" );
```

to

```
self notify( "giveLoadout", team, class, allowCopycat, setPrimarySpawnWeapon );
```

**Comment by Chenterito** [comment]
![image](https://user-images.githubusercontent.com/64875738/121889006-478a8b00-ccde-11eb-8998-a388625a5ac8.png)


The problem persists that bots appear with weapons when infected, even after making the change of ` self notify ("giveLoadout", team, class, allowCopycat, setPrimarySpawnWeapon);`

**Comment by ineedbots** [comment]
I see the issue, the bots are autoassigning and selecting a class when they shouldnt in these types of gamemodes. Expect a fix soon

**Comment by ineedbots** [comment]
deb0356181813b3a372cc25894bdca20c470c805

**Comment by Chenterito** [comment]
![image](https://user-images.githubusercontent.com/64875738/121963886-569a2900-cd30-11eb-90b1-0dcb46e12f77.png)
Now if the bots work correctly as infected.
