### ISSUE TITLE
Bot AI is pretty broken after latest Plutonium update r4043

### ISSUE THREAD

**Issue by PositronCannon** [ineedbots/piw5_bot_warfare#98]
The mod had been working perfectly fine for weeks, however when I started it up today I noticed the bots were behaving in a very strange/braindead way. They would constantly run into walls, stand in place, fire at nothing, not react to me walking right in front of them... see video:

https://www.youtube.com/watch?v=jaYAaF3Wk_g

This also happens regardless of map or game mode. Funnily enough they're still able to plant/defuse bombs in Demolition, but I think that was just sheer coincidence that one of the bots happened to end up next to a bomb site, as it only happened once.

This is on Bot Warfare 2.2.0 set up on a server, but it also happens in private match when spawning bots via the on-screen UI. On the server there were some errors showing up but I don't think they're related as they only happened on some maps and not others.

![imagen](https://github.com/ineedbots/iw5_bot_warfare/assets/65429992/2bffc482-4484-4e9f-9302-c111de9a49ba)

I can only think the latest Plutonium update must be related, as it's the only thing that changed between the last time this worked fine (less than a week ago) and now.

**Comment by crewmenkyle** [comment]
Its bugging out for me as well. I also notice that they aim at each other through the walls when I spectate them.

**Comment by Jarthuzad** [comment]
ditto, this sucks i really wanted to play with it too lol

**Comment by ramlet** [comment]
For anyone looking for a temporary fix, you can simply downgrade Plutonium and keep playing, at least private matches with bots work. Download 4035 from here https://updater-archive.plutools.pw/archives/, unzip the archive, copy and replace the files in AppData\Local\Plutonium, run plutonium-launcher-win32 in the bin folder to avoid the launcher from fetching the latest update, enjoy bot warfare again.

**Comment by ineedbots** [comment]
Use the latest commit, this is fixed on there (not v2.2.0)  I will have to release a new release here

**Comment by ineedbots** [comment]
there was viewangle changes for the bots the last pluto update also pred missile support for bots, its just not backwards compatible with old version of bot warfare

**Comment by ineedbots** [comment]
New release is out, install that, should fix your issue.

**Comment by marcusbbb12** [comment]
Okay, after updating to 2.3.0 I was still having the issue of bots being broken. I even left a comment in another ticket about it, #102. That issue was closed, but it seemed like my issue was still persisting; bots were still broken. 

For anyone who updated to 2.3.0 but still has this problem, I believe I've found a solution. Old versions of this mod required us to manually copy over 2 folders into the C:\Users\user\AppData\Local\Plutonium\storage\iw5 file path. Those folders being named bots and scripts. The new version doesn't need these folders anymore, but they still remain in that file path. If you delete those folders, the bots should be once again good to go. This also fixed another bug where the game would crash because there were be too many parent variables or something when spawning in bots.
